const codsLtx = [
     { id: 0, codeLtx: '\\times', formulaMath: '\\times' },
     { id: 1, codeLtx: '\\div', formulaMath: '\\div' },
     { id: 2, codeLtx: '\\neq', formulaMath: '\\neq' },
     { id: 3, codeLtx: '\\geq', formulaMath: '\\geq' },
     { id: 4, codeLtx: '\\leq', formulaMath: '\\leq' },
     { id: 5, codeLtx: '\\approx', formulaMath: '\\approx' },
     { id: 6, codeLtx: '\\widehat{ABC}', formulaMath: '\\widehat{ABC}' },
     { id: 7, codeLtx: '\\angle ABC', formulaMath: '\\angle ABC' },
     { id: 8, codeLtx: '\\triangle ABC', formulaMath: '\\triangle ABC' },
     { id: 9, codeLtx: '\\parallel', formulaMath: '\\parallel' },
     { id: 10, codeLtx: '\\perp', formulaMath: '\\perp' },
     { id: 11, codeLtx: '\\vec{u}', formulaMath: '\\vec{u}' },
     { id: 12, codeLtx: '\\overrightarrow{AB}', formulaMath: '\\overrightarrow{AB}' },
     { id: 13, codeLtx: '\\in', formulaMath: '\\in' },
     { id: 14, codeLtx: '\\notin', formulaMath: '\\notin' },
     { id: 15, codeLtx: '\\subset', formulaMath: '\\subset' },
     { id: 16, codeLtx: '\\subseteq', formulaMath: '\\subseteq' },
     { id: 17, codeLtx: '\\supset', formulaMath: '\\supset' },
     { id: 18, codeLtx: '\\cup', formulaMath: '\\cup' },
     { id: 19, codeLtx: '\\cap', formulaMath: '\\cap' },
     { id: 20, codeLtx: '\\emptyset', formulaMath: '\\emptyset' },
     { id: 21, codeLtx: '\\mathbb{N}', formulaMath: '\\mathbb{N}' },
     // Logique
     { id: 22, codeLtx: '\\neg p', formulaMath: '\\neg p' },
     { id: 23, codeLtx: 'p \\wedge q', formulaMath: 'p \\wedge q' },
     { id: 24, codeLtx: 'p \\vee q', formulaMath: 'p \\vee q' },
     { id: 25, codeLtx: 'p \\Rightarrow q', formulaMath: 'p \\Rightarrow q' },
     { id: 26, codeLtx: '\\implies', formulaMath: '\\implies' },
    
     { id: 27, codeLtx: '\\Longrightarrow', formulaMath: '\\Longrightarrow' },
     { id: 28, codeLtx: '\\impliedby', formulaMath: '\\impliedby' },
     { id: 29, codeLtx: '\\Longleftrightarrow', formulaMath: '\\Longleftrightarrow' },
     { id: 30, codeLtx: 'p \\Leftrightarrow q', formulaMath: 'p \\Leftrightarrow q' },
     { id: 31, codeLtx: '\\iff', formulaMath: '\\iff' },
     
     { id: 32, codeLtx: '\\forall', formulaMath: '\\forall' },
     { id: 33, codeLtx: '\\exists', formulaMath: '\\exists' },
     { id: 34, codeLtx: '\\nexists', formulaMath: '\\nexists' },
     { id: 35, codeLtx: '\\exists!', formulaMath: '\\exists!' },
];
export default codsLtx;